baseURL = '/'
languageCode = 'en-uk'
title = 'My New Hugo Site'
theme = 'hugo-universal-theme'
date_format = "YYYY-MM-DD"
author = "Romeo Dabok"
copyright = "Copyright © 2026 Pinged Technologies"
DefaultContentLanguage = "en-uk"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params]
    date_format = "YYYY-MM-DD"
    disabled_logo = false
    logo_text = "Pinged PNG"
    copyright = "Copyright © 2026 Pinged Technologies"
    logo = "img/med-logo.png"
    logo_small = "img/small-logo.png"
    style = "red"

[Params.widgets]
    search = true
    categories = true
    tags = true

[Params.topbar]
    enable = false
    text = "<p>Contact us on +420 777 555 333 or hello@universal.com.</p>"

[Params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[Params.features]
    enable = true
    cols = 3

[Params.see_more]
    enable = true
    icon = "fa fa-donate"
    title = "Contribute to our cause?"
    subtitle = "While "
    link_url = "http://your-site.com/more"
    link_text = "Check other homepages"
[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fas fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fas fa-2x fa-facebook'></i>"
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog"
    weight     = 2

[[menu.main]]
    name       = "Projects"
    identifier = "menu.projects"
    url        = "/projects"
    weight     = 3

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact"
    weight     = 4