baseURL = '/'
languageCode = 'en-uk'
title = 'My New Hugo Site'
theme = 'hugo-universal-theme'
date_format = "YYYY-MM-DD"
author = "Romeo Dabok"
copyright = "Copyright © 2026 Pinged Technologies"
DefaultContentLanguage = "en-uk"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params]
    date_format = "2006-01-02"
    disabled_logo = false
    logo_text = "Pinged PNG"
    copyright = "Copyright © 2026 Pinged Technologies"
    logo = "img/med-logo.png"
    logo_small = "img/small-logo.png"
    style = "red"
    summaryLength = 70
    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
[Params.footer.recent_posts]
    enable = true



[Params.widgets]
    search = true
    categories = true
    tags = true

[Params.topbar]
    enable = false
    text = "<p>Contact us on +420 777 555 333 or hello@universal.com.</p>"

[Params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[Params.features]
    enable = true
    cols = 3

[Params.see_more]
    enable = true
    icon = "fa fa-donate"
    title = "Contribute to our cause?"
    subtitle = "An idea without resources to back it is just a dream. To be painfully honest, since incorporation in 2022, our ideas haven't left"
    link_url = "http://your-site.com/more"
    link_text = "Check other homepages"

[Params.recent_posts]
    enable = true
    title = "Latest News"
    subtitle = "Bored already? Read some of our most recent posts on our blog..."
    hide_summary = false

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fas fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fas fa-2x fa-facebook'></i>"
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog"
    weight     = 2

[[menu.main]]
    name       = "Projects"
    identifier = "menu.projects"
    url        = "/projects"
    weight     = 3

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact"
    weight     = 4